### ISSUE TITLE
Update smith_light_limitation to allow for 0 valued inputs

### ISSUE THREAD

**Issue by radka-j** [agate-model/Agate.jl#82]
Specifically, if both alpha and maximum_growth_rate are 0 then the function should return 0 (instead of NaN as is currently the case). 

Currently, the function raises a warning if this is the case and the user is expected to pass a small number instead. Preferably, the function just returns 0 in this case (as expected).

**Comment by radka-j** [comment]
Change  current warn message to `return 0`

**Comment by ljwolf** [comment]
On this implementation: 

https://github.com/agate-model/Agate.jl/blob/8a8fd74a6dabe67e1138b760f36a9e565ba4e287/examples/N2P2ZD/functions.jl#L7
